<?php
require_once __DIR__ . '/includes/functions.php';
startSecureSession();
require_once __DIR__ . '/includes/db.php';
requireAccountant($pdo);
$uid=getLoggedInUserId(); $errors=[];
if ($_SERVER['REQUEST_METHOD']==='POST') { verifyCsrfOrFail(); $personId=(int)($_POST['person_id']??0); $name=trim((string)($_POST['name']??'')); $amount=(float)($_POST['amount']??0); $received=(string)($_POST['received_date']??date('Y-m-d')); $return=(string)($_POST['return_date']??date('Y-m-d',strtotime('+30 days'))); $type=(string)($_POST['type']??'Receive'); $method=normalizePaymentMethod((string)($_POST['method']??'cash')); $notes=trim((string)($_POST['notes']??'')); if($personId<=0)$errors[]='Select person.'; if($name==='')$errors[]='Loan name required.'; if($amount<=0)$errors[]='Amount required.'; if(!$errors){ $pdo->prepare('INSERT INTO loan (pid, name, amount, received_date, return_date, type, method, notes, uid, returned, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, NOW())')->execute([$personId,$name,$amount,$received,$return,$type,$method,$notes,$uid]); systemLog($pdo,$uid,'loan','create','Loan '.$name); setFlash('success','Loan saved.'); header('Location: loan_page.php'); exit; } }
$people=getPeople($pdo); $rows=$pdo->query('SELECT l.*, p.name AS person_name FROM loan l LEFT JOIN people p ON p.ID=l.pid ORDER BY l.ID DESC')->fetchAll();
require_once __DIR__ . '/includes/header.php';
?>
<h1 class="title">Loans</h1>
<div class="grid-2"><div class="card stack"><?php if($errors): ?><div class="alert error"><?php foreach($errors as $er): ?><div><?= e($er) ?></div><?php endforeach; ?></div><?php endif; ?><form method="post" class="stack"><?= csrfField() ?><div><label>Person</label><select name="person_id" required><option value="">Select person</option><?php foreach($people as $person): ?><option value="<?= (int)$person['ID'] ?>"><?= e($person['name']) ?> · <?= e($person['phone']) ?></option><?php endforeach; ?></select></div><div><label>Loan Name</label><input type="text" name="name" required></div><div><label>Amount</label><input type="number" step="0.01" name="amount" required></div><div class="inline-grid-2"><div><label>Received Date</label><input type="date" name="received_date" value="<?= e(date('Y-m-d')) ?>"></div><div><label>Return Date</label><input type="date" name="return_date" value="<?= e(date('Y-m-d', strtotime('+30 days'))) ?>"></div></div><div><label>Type</label><div class="grid-2"><label class="btn"><input type="radio" name="type" value="Receive" checked> Receive</label><label class="btn"><input type="radio" name="type" value="Provide"> Provide</label></div></div><div><label>Method</label><div class="grid-4"><label class="btn"><input type="radio" name="method" value="cash" checked> Cash</label><label class="btn"><input type="radio" name="method" value="bank_transfer"> Bank</label><label class="btn"><input type="radio" name="method" value="pos"> POS</label><label class="btn"><input type="radio" name="method" value="online"> Online</label></div></div><div><label>Notes</label><textarea name="notes"></textarea></div><button class="btn btn-primary" type="submit">Save Loan</button></form></div><div class="card"><h2 style="margin-top:0">Loan List</h2><div class="table-wrap"><table><thead><tr><th>Person</th><th>Loan</th><th>Amount</th><th>Received</th><th>Return</th><th>Type</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= e((string)$row['person_name']) ?></td><td><?= e((string)$row['name']) ?></td><td><?= money((float)$row['amount']) ?></td><td><?= e((string)$row['received_date']) ?></td><td><?= e((string)$row['return_date']) ?></td><td><?= e((string)$row['type']) ?></td><td><span class="tag <?= (int)$row['returned']===1?'green':'orange' ?>"><?= (int)$row['returned']===1?'Returned':'Active' ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
